# Generated by Django 2.2.17 on 2020-11-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_load_initial_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtext",
            name="jghjgkjkjhkjkhgkjhgkj",
            field=models.ManyToManyField(
                blank=True,
                related_name="customtext_jghjgkjkjhkjkhgkjhgkj",
                to="home.CustomText",
            ),
        ),
    ]
