# Generated by Django 2.2.17 on 2020-11-11 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customtext_jghjgkjkjhkjkhgkjhgkj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='jghjgkjkjhkjkhgkjhgkj',
        ),
    ]
